### ISSUE TITLE
小程序运行有报错

### ISSUE THREAD

**Issue by HealStar** [liaoxxxx/LiuJian#1]
![image](https://user-images.githubusercontent.com/16332964/99922955-2b3cf600-2d6e-11eb-97e1-e0fa2d721085.png)

**Comment by HealStar** [comment]
![image](https://user-images.githubusercontent.com/16332964/99922997-7820cc80-2d6e-11eb-80db-9ac1c837d8ec.png)

**Comment by HealStar** [comment]
09:25:48.626 正在编译中...
09:25:53.489 提示：data 作为属性保留名,不允许在自定义组件 evaluate 中定义为 props
09:25:53.496 at pages/index/goods_info.vue:1
09:25:58.146 提示：非 h5 平台 :key 不支持表达式 index-7,详情参考:https://uniapp.dcloud.io/use?id=key
09:25:58.154 at components/mx-datepicker/mx-datepicker.vue:1
09:26:02.223 Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
09:26:02.231 ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
09:26:02.232 SassError: File to import not found or unreadable: uview-ui/theme.scss.
09:26:02.241        Parent style sheet: /Users/star/Downloads/LiuJian-master/mobile/uni.scss
09:26:02.242         on line 78 of ../../../../../../Users/star/Downloads/LiuJian-master/mobile/uni.scss
09:26:02.256 >> @import 'uview-ui/theme.scss';
09:26:02.256    ^
09:26:02.273     at runLoaders (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/webpack/lib/NormalModule.js:316:20)
09:26:02.274     at /Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/loader-runner/lib/LoaderRunner.js:367:11
09:26:02.289     at /Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/loader-runner/lib/LoaderRunner.js:233:18
09:26:02.290     at context.callback (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
09:26:02.306     at Object.render [as callback] (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/sass-loader/dist/index.js:73:7)
09:26:02.307     at Object.done [as callback] (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/neo-async/async.js:8067:18)
09:26:02.323     at options.error (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/compile-node-sass/node_modules/node-sass-china/lib/index.js:294:32)
09:26:02.324 文件查找失败：'uview-ui' at main.js:17
09:26:02.339 文件查找失败：'uview-ui/components/u-grid-item/u-grid-item.vue' at pages/index/index.vue:18
09:26:02.341 文件查找失败：'uview-ui/components/u-grid/u-grid.vue' at pages/index/index.vue:13
09:26:02.356 文件查找失败：'uview-ui/components/u-icon/u-icon.vue' at pages/index/index.vue:3
09:26:02.358 文件查找失败：'uview-ui/components/u-notice-bar/u-notice-bar.vue' at pages/index/index.vue:8
09:26:02.373  ERROR  Build failed with errors.
